# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import groupChat_pb2 as groupChat__pb2


class ChatServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.chatFunction = channel.unary_unary(
                '/groupChat.ChatServer/chatFunction',
                request_serializer=groupChat__pb2.ChatInput.SerializeToString,
                response_deserializer=groupChat__pb2.ChatOutput.FromString,
                )
        self.getMessages = channel.unary_stream(
                '/groupChat.ChatServer/getMessages',
                request_serializer=groupChat__pb2.ChatInput.SerializeToString,
                response_deserializer=groupChat__pb2.ChatMessage.FromString,
                )


class ChatServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def chatFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'chatFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.chatFunction,
                    request_deserializer=groupChat__pb2.ChatInput.FromString,
                    response_serializer=groupChat__pb2.ChatOutput.SerializeToString,
            ),
            'getMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.getMessages,
                    request_deserializer=groupChat__pb2.ChatInput.FromString,
                    response_serializer=groupChat__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'groupChat.ChatServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def chatFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/groupChat.ChatServer/chatFunction',
            groupChat__pb2.ChatInput.SerializeToString,
            groupChat__pb2.ChatOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/groupChat.ChatServer/getMessages',
            groupChat__pb2.ChatInput.SerializeToString,
            groupChat__pb2.ChatMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
