# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: group_chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10group_chat.proto\x12\tgroupChat\"p\n\tChatInput\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x11\n\tgroupName\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x11\n\tmessageId\x18\x05 \x01(\x05\x12\x0c\n\x04uuid\x18\x06 \x01(\t\"T\n\nChatOutput\x12\x0e\n\x06status\x18\x01 \x01(\t\x12(\n\x08messages\x18\x02 \x03(\x0b\x32\x16.groupChat.ChatMessage\x12\x0c\n\x04user\x18\x03 \x03(\t\"O\n\x0b\x43hatMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x15\n\rnumberOfLikes\x18\x04 \x01(\x05\"\x07\n\x05\x45mpty\"N\n\x15\x43hatServerSyncRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x05\x12%\n\x07request\x18\x02 \x01(\x0b\x32\x14.groupChat.ChatInput\"(\n\x16\x43hatServerSyncResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\xe0\x01\n\nChatServer\x12=\n\x0c\x63hatFunction\x12\x14.groupChat.ChatInput\x1a\x15.groupChat.ChatOutput\"\x00\x12?\n\x0bgetMessages\x12\x14.groupChat.ChatInput\x1a\x16.groupChat.ChatMessage\"\x00\x30\x01\x12R\n\x0bsyncMessage\x12 .groupChat.ChatServerSyncRequest\x1a!.groupChat.ChatServerSyncResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'group_chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHATINPUT._serialized_start=31
  _CHATINPUT._serialized_end=143
  _CHATOUTPUT._serialized_start=145
  _CHATOUTPUT._serialized_end=229
  _CHATMESSAGE._serialized_start=231
  _CHATMESSAGE._serialized_end=310
  _EMPTY._serialized_start=312
  _EMPTY._serialized_end=319
  _CHATSERVERSYNCREQUEST._serialized_start=321
  _CHATSERVERSYNCREQUEST._serialized_end=399
  _CHATSERVERSYNCRESPONSE._serialized_start=401
  _CHATSERVERSYNCRESPONSE._serialized_end=441
  _CHATSERVER._serialized_start=444
  _CHATSERVER._serialized_end=668
# @@protoc_insertion_point(module_scope)
