# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import raft_pb2 as raft__pb2


class RaftServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.chatFunction = channel.unary_unary(
                '/raft.RaftServer/chatFunction',
                request_serializer=raft__pb2.ChatInput.SerializeToString,
                response_deserializer=raft__pb2.ChatOutput.FromString,
                )
        self.getMessages = channel.unary_stream(
                '/raft.RaftServer/getMessages',
                request_serializer=raft__pb2.ChatInput.SerializeToString,
                response_deserializer=raft__pb2.ChatMessage.FromString,
                )
        self.RequestVote = channel.unary_unary(
                '/raft.RaftServer/RequestVote',
                request_serializer=raft__pb2.RequestVoteRequest.SerializeToString,
                response_deserializer=raft__pb2.RequestVoteResponse.FromString,
                )
        self.AppendEntries = channel.unary_unary(
                '/raft.RaftServer/AppendEntries',
                request_serializer=raft__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=raft__pb2.AppendEntriesResponse.FromString,
                )
        self.ClientAppend = channel.unary_unary(
                '/raft.RaftServer/ClientAppend',
                request_serializer=raft__pb2.ClientAppendRequest.SerializeToString,
                response_deserializer=raft__pb2.ClientAppendResponse.FromString,
                )
        self.ClientRequestIndex = channel.unary_unary(
                '/raft.RaftServer/ClientRequestIndex',
                request_serializer=raft__pb2.ClientRequestIndexRequest.SerializeToString,
                response_deserializer=raft__pb2.ClientRequestIndexResponse.FromString,
                )


class RaftServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def chatFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientAppend(self, request, context):
        """these next two RPCs are sent from client to the leader
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientRequestIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'chatFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.chatFunction,
                    request_deserializer=raft__pb2.ChatInput.FromString,
                    response_serializer=raft__pb2.ChatOutput.SerializeToString,
            ),
            'getMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.getMessages,
                    request_deserializer=raft__pb2.ChatInput.FromString,
                    response_serializer=raft__pb2.ChatMessage.SerializeToString,
            ),
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=raft__pb2.RequestVoteRequest.FromString,
                    response_serializer=raft__pb2.RequestVoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=raft__pb2.AppendEntriesRequest.FromString,
                    response_serializer=raft__pb2.AppendEntriesResponse.SerializeToString,
            ),
            'ClientAppend': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientAppend,
                    request_deserializer=raft__pb2.ClientAppendRequest.FromString,
                    response_serializer=raft__pb2.ClientAppendResponse.SerializeToString,
            ),
            'ClientRequestIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientRequestIndex,
                    request_deserializer=raft__pb2.ClientRequestIndexRequest.FromString,
                    response_serializer=raft__pb2.ClientRequestIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raft.RaftServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RaftServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def chatFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raft.RaftServer/chatFunction',
            raft__pb2.ChatInput.SerializeToString,
            raft__pb2.ChatOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/raft.RaftServer/getMessages',
            raft__pb2.ChatInput.SerializeToString,
            raft__pb2.ChatMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raft.RaftServer/RequestVote',
            raft__pb2.RequestVoteRequest.SerializeToString,
            raft__pb2.RequestVoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raft.RaftServer/AppendEntries',
            raft__pb2.AppendEntriesRequest.SerializeToString,
            raft__pb2.AppendEntriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClientAppend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raft.RaftServer/ClientAppend',
            raft__pb2.ClientAppendRequest.SerializeToString,
            raft__pb2.ClientAppendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClientRequestIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/raft.RaftServer/ClientRequestIndex',
            raft__pb2.ClientRequestIndexRequest.SerializeToString,
            raft__pb2.ClientRequestIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
