# Reference from https://github.com/garutilorenzo/docker-etcd-cluster
version: "3.8"

services:
  etcd-node-0:
    image: quay.io/coreos/etcd:v3.5.0
    hostname: etcd-node-0
    command:
      - etcd
      - --name=etcd-node-0
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd-node-0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd-node-0:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd-node-0=http://etcd-node-0:2380,etcd-node-1=http://etcd-node-1:2380,etcd-node-2=http://etcd-node-2:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - etcd-cluster_data-0:/etcd/data
    networks:
      - etcd
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

  etcd-node-1:
    image: quay.io/coreos/etcd:v3.5.0
    hostname: etcd-node-1
    command:
      - etcd
      - --name=etcd-node-1
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd-node-1:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd-node-1:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd-node-0=http://etcd-node-0:2380,etcd-node-1=http://etcd-node-1:2380,etcd-node-2=http://etcd-node-2:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - etcd-cluster_data-1:/etcd/data
    networks:
      - etcd
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

  etcd-node-2:
    image: quay.io/coreos/etcd:v3.5.0
    hostname: etcd-node-2
    command:
      - etcd
      - --name=etcd-node-2
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd-node-2:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd-node-2:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd-node-0=http://etcd-node-0:2380,etcd-node-1=http://etcd-node-1:2380,etcd-node-2=http://etcd-node-2:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    volumes:
      - etcd-cluster_data-2:/etcd/data
    networks:
      - etcd
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

  nginx:
    image: nginx:alpine
    hostname: nginx-etcd
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - etcd
    ports:
      - 50051:2379
    depends_on:
      - etcd-node-0
      - etcd-node-1
      - etcd-node-2
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

volumes:
  etcd-cluster_data-0:
  etcd-cluster_data-1:
  etcd-cluster_data-2:

networks:
  etcd:
    driver: bridge
