# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"[\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"=\n\x0cVoteResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x03 \x01(\x08\"\x98\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\")\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"B\n\x15\x41ppendEntriesResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\"=\n\x10\x41\x64\x64ServerRequest\x12\x11\n\tserver_id\x18\x01 \x01(\x05\x12\x16\n\x0eserver_address\x18\x02 \x01(\t\"2\n\x11\x41\x64\x64ServerResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"(\n\x13RemoveServerRequest\x12\x11\n\tserver_id\x18\x01 \x01(\x05\"5\n\x14RemoveServerResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x93\x02\n\x04Raft\x12\x36\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x12.raft.VoteResponse\"\x00\x12J\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\"\x00\x12>\n\tAddServer\x12\x16.raft.AddServerRequest\x1a\x17.raft.AddServerResponse\"\x00\x12G\n\x0cRemoveServer\x12\x19.raft.RemoveServerRequest\x1a\x1a.raft.RemoveServerResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOTEREQUEST._serialized_start=20
  _VOTEREQUEST._serialized_end=111
  _VOTERESPONSE._serialized_start=113
  _VOTERESPONSE._serialized_end=174
  _APPENDENTRIESREQUEST._serialized_start=177
  _APPENDENTRIESREQUEST._serialized_end=329
  _LOGENTRY._serialized_start=331
  _LOGENTRY._serialized_end=372
  _APPENDENTRIESRESPONSE._serialized_start=374
  _APPENDENTRIESRESPONSE._serialized_end=440
  _ADDSERVERREQUEST._serialized_start=442
  _ADDSERVERREQUEST._serialized_end=503
  _ADDSERVERRESPONSE._serialized_start=505
  _ADDSERVERRESPONSE._serialized_end=555
  _REMOVESERVERREQUEST._serialized_start=557
  _REMOVESERVERREQUEST._serialized_end=597
  _REMOVESERVERRESPONSE._serialized_start=599
  _REMOVESERVERRESPONSE._serialized_end=652
  _RAFT._serialized_start=655
  _RAFT._serialized_end=930
# @@protoc_insertion_point(module_scope)
